export default {
  cardOperationFees: {
    error: null,
    loading: false,
    success: false,
    message: '',
    Fees: '',
    TotalAmount: '',
    Currency: '',
    justAdded: false,
  },
  payPalOperationFees: {
    error: null,
    loading: false,
    success: false,
    message: '',
    Fees: '',
    TotalAmount: '',
    Currency: '',
    justAdded: false,
  },
  addMoneyFromCreditCard: {
    error: null,
    loading: false,
    success: false,
    justAdded: false,
    data: null,
  },
  addMoneyFromPayPal: {
    error: null,
    loading: false,
    success: false,
    justAdded: false,
    data: null,
  },
};
