export default [
  {
    text: 'Afghanistan',
    key: 'Afghanistan',
    flag: 'af',
    value: 'af',
  },
  {
    text: 'Aland Islands',
    key: 'Aland Islands',
    flag: 'ax',
    value: 'ax',
  },
  { text: 'Albania', key: 'Albania', flag: 'al', value: 'al' },
  { text: 'Algeria', key: 'Algeria', flag: 'dz', value: 'dz' },
  {
    text: 'American Samoa',
    key: 'American Samoa',
    flag: 'as',
    value: 'as',
  },
  { text: 'Andorra', key: 'Andorra', flag: 'ad', value: 'ad' },
  { text: 'Angola', key: 'Angola', flag: 'ao', value: 'ao' },
  { text: 'Anguilla', key: 'Anguilla', flag: 'ai', value: 'ai' },
  { text: 'Antigua', key: 'Antigua', flag: 'ag', value: 'ag' },
  { text: 'Argentina', key: 'Argentina', flag: 'ar', value: 'ar' },
  { text: 'Armenia', key: 'Armenia', flag: 'am', value: 'am' },
  { text: 'Aruba', key: 'Aruba', flag: 'aw', value: 'aw' },
  { text: 'Australia', key: 'Australia', flag: 'au', value: 'au' },
  { text: 'Austria', key: 'Austria', flag: 'at', value: 'at' },
  {
    text: 'Azerbaijan',
    key: 'Azerbaijan',
    flag: 'az',
    value: 'az',
  },
  { text: 'Bahamas', key: 'Bahamas', flag: 'bs', value: 'bs' },
  { text: 'Bahrain', key: 'Bahrain', flag: 'bh', value: 'bh' },
  {
    text: 'Bangladesh',
    key: 'Bangladesh',
    flag: 'bd',
    value: 'bd',
  },
  { text: 'Barbados', key: 'Barbados', flag: 'bb', value: 'bb' },
  { text: 'Belarus', key: 'Belarus', flag: 'by', value: 'by' },
  { text: 'Belgium', key: 'Belgium', flag: 'be', value: 'be' },
  { text: 'Belize', key: 'Belize', flag: 'bz', value: 'bz' },
  { text: 'Benin', key: 'Benin', flag: 'bj', value: 'bj' },
  { text: 'Bermuda', key: 'Bermuda', flag: 'bm', value: 'bm' },
  { text: 'Bhutan', key: 'Bhutan', flag: 'bt', value: 'bt' },
  { text: 'Bolivia', key: 'Bolivia', flag: 'bo', value: 'bo' },
  { text: 'Bosnia', key: 'Bosnia', flag: 'ba', value: 'ba' },
  { text: 'Botswana', key: 'Botswana', flag: 'bw', value: 'bw' },
  {
    text: 'Bouvet Island',
    key: 'Bouvet Island',
    flag: 'bv',
    value: 'bv',
  },
  { text: 'Brazil', key: 'Brazil', flag: 'br', value: 'br' },
  {
    text: 'British Virgin Islands',
    key: 'British Virgin Islands',
    flag: 'vg',
    value: 'vg',
  },
  { text: 'Brunei', key: 'Brunei', flag: 'bn', value: 'bn' },
  { text: 'Bulgaria', key: 'Bulgaria', flag: 'bg', value: 'bg' },
  {
    text: 'Burkina Faso',
    key: 'Burkina Faso',
    flag: 'bf',
    value: 'bf',
  },
  { text: 'Burma', key: 'Burma', flag: 'mm', value: 'mm' },
  { text: 'Burundi', key: 'Burundi', flag: 'bi', value: 'bi' },
  {
    text: 'Caicos Islands',
    key: 'Caicos Islands',
    flag: 'tc',
    value: 'tc',
  },
  { text: 'Cambodia', key: 'Cambodia', flag: 'kh', value: 'kh' },
  { text: 'Cameroon', key: 'Cameroon', flag: 'cm', value: 'cm' },
  { text: 'Canada', key: 'Canada', flag: 'ca', value: 'ca' },
  {
    text: 'Cape Verde',
    key: 'Cape Verde',
    flag: 'cv',
    value: 'cv',
  },
  {
    text: 'Cayman Islands',
    key: 'Cayman Islands',
    flag: 'ky',
    value: 'ky',
  },
  {
    text: 'Central African Republic',
    key: 'Central African Republic',
    flag: 'cf',
    value: 'cf',
  },
  { text: 'Chad', key: 'Chad', flag: 'td', value: 'td' },
  { text: 'Chile', key: 'Chile', flag: 'cl', value: 'cl' },
  { text: 'China', key: 'China', flag: 'cn', value: 'cn' },
  {
    text: 'Christmas Island',
    key: 'Christmas Island',
    flag: 'cx',
    value: 'cx',
  },
  {
    text: 'Cocos Islands',
    key: 'Cocos Islands',
    flag: 'cc',
    value: 'cc',
  },
  { text: 'Colombia', key: 'Colombia', flag: 'co', value: 'co' },
  { text: 'Comoros', key: 'Comoros', flag: 'km', value: 'km' },
  { text: 'Congo', key: 'Congo', flag: 'cd', value: 'cd' },
  {
    text: 'Congo Brazzaville',
    key: 'Congo Brazzaville',
    flag: 'cg',
    value: 'cg',
  },
  {
    text: 'Cook Islands',
    key: 'Cook Islands',
    flag: 'ck',
    value: 'ck',
  },
  {
    text: 'Costa Rica',
    key: 'Costa Rica',
    flag: 'cr',
    value: 'cr',
  },
  {
    text: 'Cote Divoire',
    key: 'Cote Divoire',
    flag: 'ci',
    value: 'ci',
  },
  { text: 'Croatia', key: 'Croatia', flag: 'hr', value: 'hr' },
  { text: 'Cuba', key: 'Cuba', flag: 'cu', value: 'cu' },
  { text: 'Cyprus', key: 'Cyprus', flag: 'cy', value: 'cy' },
  {
    text: 'Czech Republic',
    key: 'Czech Republic',
    flag: 'cz',
    value: 'cz',
  },
  { text: 'Denmark', key: 'Denmark', flag: 'dk', value: 'dk' },
  { text: 'Djibouti', key: 'Djibouti', flag: 'dj', value: 'dj' },
  { text: 'Dominica', key: 'Dominica', flag: 'dm', value: 'dm' },
  {
    text: 'Dominican Republic',
    key: 'Dominican Republic',
    flag: 'do',
    value: 'do',
  },
  { text: 'Ecuador', key: 'Ecuador', flag: 'ec', value: 'ec' },
  { text: 'Egypt', key: 'Egypt', flag: 'eg', value: 'eg' },
  {
    text: 'El Salvador',
    key: 'El Salvador',
    flag: 'sv',
    value: 'sv',
  },
  {
    text: 'Equatorial Guinea',
    key: 'Equatorial Guinea',
    flag: 'gq',
    value: 'gq',
  },
  { text: 'Eritrea', key: 'Eritrea', flag: 'er', value: 'er' },
  { text: 'Estonia', key: 'Estonia', flag: 'ee', value: 'ee' },
  { text: 'Ethiopia', key: 'Ethiopia', flag: 'et', value: 'et' },
  {
    text: 'Europeanunion',
    key: 'Europeanunion',
    flag: 'eu',
    value: 'eu',
  },
  {
    text: 'Falkland Islands',
    key: 'Falkland Islands',
    flag: 'fk',
    value: 'fk',
  },
  {
    text: 'Faroe Islands',
    key: 'Faroe Islands',
    flag: 'fo',
    value: 'fo',
  },
  { text: 'Fiji', key: 'Fiji', flag: 'fj', value: 'fj' },
  { text: 'Finland', key: 'Finland', flag: 'fi', value: 'fi' },
  { text: 'France', key: 'France', flag: 'fr', value: 'fr' },
  {
    text: 'French Guiana',
    key: 'French Guiana',
    flag: 'gf',
    value: 'gf',
  },
  {
    text: 'French Polynesia',
    key: 'French Polynesia',
    flag: 'pf',
    value: 'pf',
  },
  {
    text: 'French Territories',
    key: 'French Territories',
    flag: 'tf',
    value: 'tf',
  },
  { text: 'Gabon', key: 'Gabon', flag: 'ga', value: 'ga' },
  { text: 'Gambia', key: 'Gambia', flag: 'gm', value: 'gm' },
  { text: 'Georgia', key: 'Georgia', flag: 'ge', value: 'ge' },
  { text: 'Germany', key: 'Germany', flag: 'de', value: 'de' },
  { text: 'Ghana', key: 'Ghana', flag: 'gh', value: 'gh' },
  { text: 'Gibraltar', key: 'Gibraltar', flag: 'gi', value: 'gi' },
  { text: 'Greece', key: 'Greece', flag: 'gr', value: 'gr' },
  { text: 'Greenland', key: 'Greenland', flag: 'gl', value: 'gl' },
  { text: 'Grenada', key: 'Grenada', flag: 'gd', value: 'gd' },
  {
    text: 'Guadeloupe',
    key: 'Guadeloupe',
    flag: 'gp',
    value: 'gp',
  },
  { text: 'Guam', key: 'Guam', flag: 'gu', value: 'gu' },
  { text: 'Guatemala', key: 'Guatemala', flag: 'gt', value: 'gt' },
  { text: 'Guinea', key: 'Guinea', flag: 'gn', value: 'gn' },
  {
    text: 'Guinea-Bissau',
    key: 'Guinea-Bissau',
    flag: 'gw',
    value: 'gw',
  },
  { text: 'Guyana', key: 'Guyana', flag: 'gy', value: 'gy' },
  { text: 'Haiti', key: 'Haiti', flag: 'ht', value: 'ht' },
  {
    text: 'Heard Island',
    key: 'Heard Island',
    flag: 'hm',
    value: 'hm',
  },
  { text: 'Honduras', key: 'Honduras', flag: 'hn', value: 'hn' },
  { text: 'Hong Kong', key: 'Hong Kong', flag: 'hk', value: 'hk' },
  { text: 'Hungary', key: 'Hungary', flag: 'hu', value: 'hu' },
  { text: 'Iceland', key: 'Iceland', flag: 'is', value: 'is' },
  { text: 'India', key: 'India', flag: 'in', value: 'in' },
  {
    text: 'Indian Ocean Territory',
    key: 'Indian Ocean Territory',
    flag: 'io',
    value: 'io',
  },
  { text: 'Indonesia', key: 'Indonesia', flag: 'id', value: 'id' },
  { text: 'Iran', key: 'Iran', flag: 'ir', value: 'ir' },
  { text: 'Iraq', key: 'Iraq', flag: 'iq', value: 'iq' },
  { text: 'Ireland', key: 'Ireland', flag: 'ie', value: 'ie' },
  { text: 'Israel', key: 'Israel', flag: 'il', value: 'il' },
  { text: 'Italy', key: 'Italy', flag: 'it', value: 'it' },
  { text: 'Jamaica', key: 'Jamaica', flag: 'jm', value: 'jm' },
  { text: 'Jan Mayen', key: 'Jan Mayen', flag: 'sj', value: 'sj' },
  { text: 'Japan', key: 'Japan', flag: 'jp', value: 'jp' },
  { text: 'Jordan', key: 'Jordan', flag: 'jo', value: 'jo' },
  {
    text: 'Kazakhstan',
    key: 'Kazakhstan',
    flag: 'kz',
    value: 'kz',
  },
  { text: 'Kenya', key: 'Kenya', flag: 'ke', value: 'ke' },
  { text: 'Kiribati', key: 'Kiribati', flag: 'ki', value: 'ki' },
  { text: 'Kuwait', key: 'Kuwait', flag: 'kw', value: 'kw' },
  {
    text: 'Kyrgyzstan',
    key: 'Kyrgyzstan',
    flag: 'kg',
    value: 'kg',
  },
  { text: 'Laos', key: 'Laos', flag: 'la', value: 'la' },
  { text: 'Latvia', key: 'Latvia', flag: 'lv', value: 'lv' },
  { text: 'Lebanon', key: 'Lebanon', flag: 'lb', value: 'lb' },
  { text: 'Lesotho', key: 'Lesotho', flag: 'ls', value: 'ls' },
  { text: 'Liberia', key: 'Liberia', flag: 'lr', value: 'lr' },
  { text: 'Libya', key: 'Libya', flag: 'ly', value: 'ly' },
  {
    text: 'Liechtenstein',
    key: 'Liechtenstein',
    flag: 'li',
    value: 'li',
  },
  { text: 'Lithuania', key: 'Lithuania', flag: 'lt', value: 'lt' },
  {
    text: 'Luxembourg',
    key: 'Luxembourg',
    flag: 'lu',
    value: 'lu',
  },
  { text: 'Macau', key: 'Macau', flag: 'mo', value: 'mo' },
  { text: 'Macedonia', key: 'Macedonia', flag: 'mk', value: 'mk' },
  {
    text: 'Madagascar',
    key: 'Madagascar',
    flag: 'mg',
    value: 'mg',
  },
  { text: 'Malawi', key: 'Malawi', flag: 'mw', value: 'mw' },
  { text: 'Malaysia', key: 'Malaysia', flag: 'my', value: 'my' },
  { text: 'Maldives', key: 'Maldives', flag: 'mv', value: 'mv' },
  { text: 'Mali', key: 'Mali', flag: 'ml', value: 'ml' },
  { text: 'Malta', key: 'Malta', flag: 'mt', value: 'mt' },
  {
    text: 'Marshall Islands',
    key: 'Marshall Islands',
    flag: 'mh',
    value: 'mh',
  },
  {
    text: 'Martinique',
    key: 'Martinique',
    flag: 'mq',
    value: 'mq',
  },
  {
    text: 'Mauritania',
    key: 'Mauritania',
    flag: 'mr',
    value: 'mr',
  },
  { text: 'Mauritius', key: 'Mauritius', flag: 'mu', value: 'mu' },
  { text: 'Mayotte', key: 'Mayotte', flag: 'yt', value: 'yt' },
  { text: 'Mexico', key: 'Mexico', flag: 'mx', value: 'mx' },
  {
    text: 'Micronesia',
    key: 'Micronesia',
    flag: 'fm',
    value: 'fm',
  },
  { text: 'Moldova', key: 'Moldova', flag: 'md', value: 'md' },
  { text: 'Monaco', key: 'Monaco', flag: 'mc', value: 'mc' },
  { text: 'Mongolia', key: 'Mongolia', flag: 'mn', value: 'mn' },
  {
    text: 'Montenegro',
    key: 'Montenegro',
    flag: 'me',
    value: 'me',
  },
  {
    text: 'Montserrat',
    key: 'Montserrat',
    flag: 'ms',
    value: 'ms',
  },
  { text: 'Morocco', key: 'Morocco', flag: 'ma', value: 'ma' },
  {
    text: 'Mozambique',
    key: 'Mozambique',
    flag: 'mz',
    value: 'mz',
  },
  { text: 'Namibia', key: 'Namibia', flag: 'na', value: 'na' },
  { text: 'Nauru', key: 'Nauru', flag: 'nr', value: 'nr' },
  { text: 'Nepal', key: 'Nepal', flag: 'np', value: 'np' },
  {
    text: 'Netherlands',
    key: 'Netherlands',
    flag: 'nl',
    value: 'nl',
  },
  {
    text: 'Netherlandsantilles',
    key: 'Netherlandsantilles',
    flag: 'an',
    value: 'an',
  },
  {
    text: 'New Caledonia',
    key: 'New Caledonia',
    flag: 'nc',
    value: 'nc',
  },
  {
    text: 'New Guinea',
    key: 'New Guinea',
    flag: 'pg',
    value: 'pg',
  },
  {
    text: 'New Zealand',
    key: 'New Zealand',
    flag: 'nz',
    value: 'nz',
  },
  { text: 'Nicaragua', key: 'Nicaragua', flag: 'ni', value: 'ni' },
  { text: 'Niger', key: 'Niger', flag: 'ne', value: 'ne' },
  { text: 'Nigeria', key: 'Nigeria', flag: 'ng', value: 'ng' },
  { text: 'Niue', key: 'Niue', flag: 'nu', value: 'nu' },
  {
    text: 'Norfolk Island',
    key: 'Norfolk Island',
    flag: 'nf',
    value: 'nf',
  },
  {
    text: 'North Korea',
    key: 'North Korea',
    flag: 'kp',
    value: 'kp',
  },
  {
    text: 'Northern Mariana Islands',
    key: 'Northern Mariana Islands',
    flag: 'mp',
    value: 'mp',
  },
  { text: 'Norway', key: 'Norway', flag: 'no', value: 'no' },
  { text: 'Oman', key: 'Oman', flag: 'om', value: 'om' },
  { text: 'Pakistan', key: 'Pakistan', flag: 'pk', value: 'pk' },
  { text: 'Palau', key: 'Palau', flag: 'pw', value: 'pw' },
  { text: 'Palestine', key: 'Palestine', flag: 'ps', value: 'ps' },
  { text: 'Panama', key: 'Panama', flag: 'pa', value: 'pa' },
  { text: 'Paraguay', key: 'Paraguay', flag: 'py', value: 'py' },
  { text: 'Peru', key: 'Peru', flag: 'pe', value: 'pe' },
  {
    text: 'Philippines',
    key: 'Philippines',
    flag: 'ph',
    value: 'ph',
  },
  {
    text: 'Pitcairn Islands',
    key: 'Pitcairn Islands',
    flag: 'pn',
    value: 'pn',
  },
  { text: 'Poland', key: 'Poland', flag: 'pl', value: 'pl' },
  { text: 'Portugal', key: 'Portugal', flag: 'pt', value: 'pt' },
  {
    text: 'Puerto Rico',
    key: 'Puerto Rico',
    flag: 'pr',
    value: 'pr',
  },
  { text: 'Qatar', key: 'Qatar', flag: 'qa', value: 'qa' },
  { text: 'Reunion', key: 'Reunion', flag: 're', value: 're' },
  { text: 'Romania', key: 'Romania', flag: 'ro', value: 'ro' },
  { text: 'Russia', key: 'Russia', flag: 'ru', value: 'ru' },
  { text: 'Rwanda', key: 'Rwanda', flag: 'rw', value: 'rw' },
  {
    text: 'Saint Helena',
    key: 'Saint Helena',
    flag: 'sh',
    value: 'sh',
  },
  {
    text: 'Saint Kitts and Nevis',
    key: 'Saint Kitts and Nevis',
    flag: 'kn',
    value: 'kn',
  },
  {
    text: 'Saint Lucia',
    key: 'Saint Lucia',
    flag: 'lc',
    value: 'lc',
  },
  {
    text: 'Saint Pierre',
    key: 'Saint Pierre',
    flag: 'pm',
    value: 'pm',
  },
  {
    text: 'Saint Vincent',
    key: 'Saint Vincent',
    flag: 'vc',
    value: 'vc',
  },
  { text: 'Samoa', key: 'Samoa', flag: 'ws', value: 'ws' },
  {
    text: 'San Marino',
    key: 'San Marino',
    flag: 'sm',
    value: 'sm',
  },
  {
    text: 'Sandwich Islands',
    key: 'Sandwich Islands',
    flag: 'gs',
    value: 'gs',
  },
  { text: 'Sao Tome', key: 'Sao Tome', flag: 'st', value: 'st' },
  {
    text: 'Saudi Arabia',
    key: 'Saudi Arabia',
    flag: 'sa',
    value: 'sa',
  },
  {
    text: 'Scotland',
    key: 'Scotland',
    flag: 'gb sct',
    value: 'gb sct',
  },
  { text: 'Senegal', key: 'Senegal', flag: 'sn', value: 'sn' },
  { text: 'Serbia', key: 'Serbia', flag: 'rs', value: 'rs' },
  {
    text: 'Seychelles',
    key: 'Seychelles',
    flag: 'sc',
    value: 'sc',
  },
  {
    text: 'Sierra Leone',
    key: 'Sierra Leone',
    flag: 'sl',
    value: 'sl',
  },
  { text: 'Singapore', key: 'Singapore', flag: 'sg', value: 'sg' },
  { text: 'Slovakia', key: 'Slovakia', flag: 'sk', value: 'sk' },
  { text: 'Slovenia', key: 'Slovenia', flag: 'si', value: 'si' },
  {
    text: 'Solomon Islands',
    key: 'Solomon Islands',
    flag: 'sb',
    value: 'sb',
  },
  { text: 'Somalia', key: 'Somalia', flag: 'so', value: 'so' },
  {
    text: 'South Africa',
    key: 'South Africa',
    flag: 'za',
    value: 'za',
  },
  {
    text: 'South Korea',
    key: 'South Korea',
    flag: 'kr',
    value: 'kr',
  },
  { text: 'Spain', key: 'Spain', flag: 'es', value: 'es' },
  { text: 'Sri Lanka', key: 'Sri Lanka', flag: 'lk', value: 'lk' },
  { text: 'Sudan', key: 'Sudan', flag: 'sd', value: 'sd' },
  { text: 'Suriname', key: 'Suriname', flag: 'sr', value: 'sr' },
  { text: 'Swaziland', key: 'Swaziland', flag: 'sz', value: 'sz' },
  { text: 'Sweden', key: 'Sweden', flag: 'se', value: 'se' },
  {
    text: 'Switzerland',
    key: 'Switzerland',
    flag: 'ch',
    value: 'ch',
  },
  { text: 'Syria', key: 'Syria', flag: 'sy', value: 'sy' },
  { text: 'Taiwan', key: 'Taiwan', flag: 'tw', value: 'tw' },
  {
    text: 'Tajikistan',
    key: 'Tajikistan',
    flag: 'tj',
    value: 'tj',
  },
  { text: 'Tanzania', key: 'Tanzania', flag: 'tz', value: 'tz' },
  { text: 'Thailand', key: 'Thailand', flag: 'th', value: 'th' },
  {
    text: 'Timorleste',
    key: 'Timorleste',
    flag: 'tl',
    value: 'tl',
  },
  { text: 'Togo', key: 'Togo', flag: 'tg', value: 'tg' },
  { text: 'Tokelau', key: 'Tokelau', flag: 'tk', value: 'tk' },
  { text: 'Tonga', key: 'Tonga', flag: 'to', value: 'to' },
  { text: 'Trinidad', key: 'Trinidad', flag: 'tt', value: 'tt' },
  { text: 'Tunisia', key: 'Tunisia', flag: 'tn', value: 'tn' },
  { text: 'Turvalue', key: 'Turvalue', flag: 'tr', value: 'tr' },
  {
    text: 'Turkmenistan',
    key: 'Turkmenistan',
    flag: 'tm',
    value: 'tm',
  },
  { text: 'Tuvalu', key: 'Tuvalu', flag: 'tv', value: 'tv' },
  {
    text: 'United Arab Emirates',
    key: 'United Arab Emirates',
    flag: 'ae',
    value: 'ae',
  },
  { text: 'Uganda', key: 'Uganda', flag: 'ug', value: 'ug' },
  { text: 'Ukraine', key: 'Ukraine', flag: 'ua', value: 'ua' },
  {
    text: 'United Kingdom',
    key: 'United Kingdom',
    flag: 'gb',
    value: 'gb',
  },
  {
    text: 'United States',
    key: 'United States',
    flag: 'us',
    value: 'us',
  },
  { text: 'Uruguay', key: 'Uruguay', flag: 'uy', value: 'uy' },
  {
    text: 'US Minor Islands',
    key: 'US Minor Islands',
    flag: 'um',
    value: 'um',
  },
  {
    text: 'US Virgin Islands',
    key: 'US Virgin Islands',
    flag: 'vi',
    value: 'vi',
  },
  {
    text: 'Uzbekistan',
    key: 'Uzbekistan',
    flag: 'uz',
    value: 'uz',
  },
  { text: 'Vanuatu', key: 'Vanuatu', flag: 'vu', value: 'vu' },
  {
    text: 'Vatican City',
    key: 'Vatican City',
    flag: 'va',
    value: 'va',
  },
  { text: 'Venezuela', key: 'Venezuela', flag: 've', value: 've' },
  { text: 'Vietnam', key: 'Vietnam', flag: 'vn', value: 'vn' },
  { text: 'Wales', key: 'Wales', flag: 'gb wls', value: 'gb wls' },
  {
    text: 'Wallis and Futuna',
    key: 'Wallis and Futuna',
    flag: 'wf',
    value: 'wf',
  },
  {
    text: 'Western Sahara',
    key: 'Western Sahara',
    flag: 'eh',
    value: 'eh',
  },
  { text: 'Yemen', key: 'Yemen', flag: 'ye', value: 'ye' },
  { text: 'Zambia', key: 'Zambia', flag: 'zm', value: 'zm' },
  { text: 'Zimbabwe', key: 'Zimbabwe', flag: 'zw', value: 'zw' },
];
